# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/lib-auth" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/lib-clients" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/lib-email" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/lib-entra" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/lib-google-cloud-storage" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/lib-keycloak-client" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/lib-nats" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/lib-schemas" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/lib-slack-notifier" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/lib-sql" # Location of package manifests
    schedule:
      interval: "daily"
