[package]
name = "lib-google-cloud-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
google-cloud-storage = "1.8.0"
google-cloud-auth = "1.6"
bytes = "1.11.1"
serde_json = "1.0.149"
